name: whats_up

description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #state management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3

  #firebase
  firebase_auth: ^3.6.3
  cloud_firestore: ^3.4.4
  firebase_storage: ^10.3.5

  responsive_builder: ^0.4.2
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3 #message shape bubble

  bubble: ^1.1.9+1

  country_pickers: ^2.0.0
  masked_text_input_formatter: ^0.0.1
  pin_code_fields: ^7.4.0

  get_it: ^7.2.0
  contacts_service: ^0.6.3
  font_awesome_flutter: ^10.1.0

  #dateFormat
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
